### PR TITLE
Add support for Laravel 5.6

### PR DESCRIPTION
**Pull request by AlexMac7**
This PR will add support for Laravel 5.6.

### CODE REVIEW

**Comment by zschuessler** [comment]
Thank you for the PR!!

Cheers.

**Comment by jkudish** [comment]
Thanks for the merge @zschuessler can you make a release please?

**Comment by zschuessler** [comment]
Done!
https://packagist.org/packages/zschuessler/laravel-route-to-class

Thanks for the heads up.

**Comment by jkudish** [comment]
Awesome, thanks :)

**Pull request merged**
